### ISSUE TITLE
Support the Kube health probes for startup, readiness and liveness

### ISSUE THREAD

**Issue by jwalcorn** [IBMStockTrader/stock-quote-spring#2]
My operator configures Stock Quote with the following yaml (see https://github.com/IBMStockTrader/stocktrader-operator/blob/master/helm-charts/stocktrader/templates/stock-quote.yaml).  Need these three endpoints implemented, so that we can enable the Kube HorizontalPodAutoscaler for this microservice:

```
        startupProbe:
          httpGet:
            path: /health/started
            port: 9080
          initialDelaySeconds: 60
          periodSeconds: 30
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 9080
          periodSeconds: 15
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health/live
            port: 9080
          periodSeconds: 15
          failureThreshold: 3

**Comment by jwalcorn** [comment]
note we use port 9080 (the default http port for Open Liberty).  so Spring will need to be told to switch from its default port of 8080 to the one we're expecting here

**Comment by jwalcorn** [comment]
this looks related: https://spring.io/blog/2020/03/25/liveness-and-readiness-probes-with-spring-boot

**Comment by sigfrido45** [comment]
Unfornately those ready checks is for spring boot version >=2.3.x  and we are using 2.0.2.RELEASE version

**Comment by jwalcorn** [comment]
Your PR worked great.  Thanks @sigfrido45!
