### ISSUE TITLE
Adding dummy property in Account model for increase payload size in decryption - updating redisson version

### ISSUE THREAD

**Issue by sigfrido45** [IBMStockTrader/stock-quote-spring#6]

**Comment by sigfrido45** [comment]
Adding a property for using the dummy text in application.yml
Dummy text added in resources/static/lorem.text -> only read once
Dummy text initially with 20 000 bytes

**Comment by sigfrido45** [comment]
Changing redisson version to  3.15.0
Changing file size to 300K

**Comment by jwalcorn** [comment]
Looks good.  We saw a 3 ms penalty for decrypting 300 KB cache entries, and a 9 ms penalty for 1 MB, in Azure Cache with our Gatling run simulating 200 concurrent users for an hour for each test run.  Thanks Cristhian for making these updates so we could gather this data quickly for the customer!

<img width="733" alt="image" src="https://user-images.githubusercontent.com/28963246/198356062-8748921d-07e8-4ca9-8029-a065cb7ba7ca.png">
